mutation UpdateFacture($id: ID!, $input: UpdateFactureInput!) {
  updateFacture(id: $id, input: $input) {
    id
    factureNumber
    products {
      productId
      product {
        id
        name
        mark
        priceVente
        priceAchat
        stock
        storeId
        createdAt
        updatedAt
      }
      quantity
      price
    }
    quantity
    date
    price
    currency
    client {
      id
      name
      phone
      storeId
      createdAt
      updatedAt
    }
    storeId
    store {
      id
      name
      address
      phone
      companyId
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}



